# Generated by Django 3.0.13 on 2021-03-29 19:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210329_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.CharField(max_length=50),
        ),
    ]
