# Generated by Django 3.0.13 on 2021-04-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20210331_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
