# Generated by Django 3.1.7 on 2021-03-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210309_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.TextField(blank=True, max_length=300, null=True)),
                ('store_name', models.TextField(blank=True, max_length=300, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('payment_method', models.TextField(blank=True, max_length=255, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
