# Generated by Django 3.0.13 on 2021-03-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprofile',
            name='profile',
        ),
    ]
