# Generated by Django 3.0.13 on 2021-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productprofile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
