# Generated by Django 3.1.7 on 2021-03-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210309_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_system',
        ),
    ]
