# Generated by Django 3.1.7 on 2021-03-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210311_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_system',
            new_name='username',
        ),
    ]
