# Generated by Django 3.0.13 on 2021-03-29 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210329_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
