# Generated by Django 3.0.13 on 2021-03-30 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_remove_productcart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
