# Generated by Django 3.1.7 on 2021-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210309_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprofile',
            options={'verbose_name_plural': 'Products Profile'},
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='address',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='segment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
