# Generated by Django 3.1.7 on 2021-03-11 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210309_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='date_product',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
