# Generated by Django 3.1.7 on 2021-03-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210310_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprofile',
            name='published',
        ),
    ]
