# Generated by Django 3.1.7 on 2021-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productprofile_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
