# Generated by Django 3.0.13 on 2021-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210321_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofile',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('Ticket', 'Ticket'), ('Credit card | debit', 'Credit card | debit'), ('Exchange involving product', 'Exchange involving product')], max_length=100),
        ),
    ]
