# Generated by Django 3.0.13 on 2021-03-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210324_1929'),
        ('products', '0019_remove_productprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
            preserve_default=False,
        ),
    ]
