# Generated by Django 3.0.13 on 2021-03-28 00:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
