# Generated by Django 3.0.13 on 2021-03-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productprofile_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprofile',
            name='quantity',
        ),
    ]
