# Generated by Django 3.1.7 on 2021-03-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210308_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='store_name',
        ),
    ]
