# Generated by Django 3.1.7 on 2021-03-11 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20210311_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=20)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address Users',
            },
        ),
    ]
