# Generated by Django 3.0.13 on 2021-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210311_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cell_phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
